# Generated by Django 4.2.4 on 2024-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_favoritebook_delete_downloadedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
